<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- اطلاعات پکیج -->
		<PackageId>KernelAbstractions.Patterns</PackageId>
		<Version>1.0.0</Version>
		<Authors>HoseinTorkan</Authors>
		<Description>Common design patterns (Result Pattern, etc.) for .NET applications.</Description>

		<!-- آدرس مخزن کد -->
		<RepositoryUrl>https://github.com/HoseinTorkan/KernelAbstractions</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<!-- تگ‌های جستجو -->
		<PackageTags>result-pattern;patterns;clean-architecture</PackageTags>
	</PropertyGroup>

</Project>